4-module's tasks & 5-module's tasks
js-tasks-ru/jsbasic-20240115_ilyachever pull request #5
Opened 2024-02-10 09:33 UTC by ilyachever

2024-02-10 09:34 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2024-02-10 09:49 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2024-02-10 13:10 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2024-02-10 13:14 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2024-02-10 13:18 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2024-02-10 13:27 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2024-02-11 15:46 UTC, SinimaWath requested changes

2024-02-11 15:46 UTC, SinimaWath commented on 4-module/3-task/index.js
> +    if (!Boolean('available' in element.dataset)) parentElement.setAttribute('hidden', true);
`'available' in element.dataset` - эта операция, вовзращает true/false, так что тут нет смысла в `!Boolean(...)`

2024-02-11 15:46 UTC, SinimaWath commented on 5-module/2-task/index.js
> +  if (!textElement) return;
Вот эту запись можно было заменить на: `event.currentTarget`:
```
function toggleElementVisibility(event) {
 event.currentTarget.hidden = !event.currentTarget.hidden
}
```

2024-02-12 20:33 UTC, SinimaWath approved these changes

2024-02-12 20:33 UTC, merged